/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class Administrador_Desbloqueos extends javax.swing.JPanel {

    private String nombreLaboratorio;

    /**
     * Creates new form Administrador_Desbloqueos
     */
    public Administrador_Desbloqueos(String nombreLab) {
        initComponents();
        if (lbllaboratorio != null) {
            lbllaboratorio.setText(nombreLab);
        }
        nombreLaboratorio = nombreLab;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        panellateral = new javax.swing.JPanel();
        panelcontnedoropciones = new javax.swing.JPanel();
        btnequipos = new javax.swing.JButton();
        btnbloqueos = new javax.swing.JButton();
        lbldesbloqueos = new javax.swing.JLabel();
        panelsuperior = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lbllaboratorio = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbladmin = new javax.swing.JLabel();
        jpanelcontenido = new javax.swing.JPanel();
        contenedorbloqueospendientes = new javax.swing.JPanel();
        lblbloqueospendientes = new javax.swing.JLabel();
        lblnumerodebloqueos = new javax.swing.JLabel();
        contenedordecontenido = new javax.swing.JPanel();
        lblmotivos = new javax.swing.JLabel();
        cbxsanciones = new javax.swing.JComboBox<>();
        lblbuscaralumno = new javax.swing.JLabel();
        txtbuscadoralumno = new javax.swing.JTextField();
        btnfltrar = new javax.swing.JButton();
        btnrestaurartabla = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladesbloqueos = new javax.swing.JTable();
        contenedordesbloqueorapido = new javax.swing.JPanel();
        lbltitulodesbloqueorapido = new javax.swing.JLabel();
        lblidalumno = new javax.swing.JLabel();
        txtidalumno = new javax.swing.JTextField();
        btnaplicardesbloqueo = new javax.swing.JButton();
        lblinstrucciones = new javax.swing.JLabel();
        lblpaginas = new javax.swing.JLabel();
        btnizquierda = new javax.swing.JButton();
        btnderecha = new javax.swing.JButton();

        panelfondo.setBackground(new java.awt.Color(255, 51, 51));
        panelfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellateral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));

        btnequipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnequipos.setForeground(new java.awt.Color(102, 102, 102));
        btnequipos.setText("Equipos");
        btnequipos.setBorder(null);
        btnequipos.setContentAreaFilled(false);
        btnequipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnequipos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnequipos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnequipos.setInheritsPopupMenu(true);

        btnbloqueos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnbloqueos.setForeground(new java.awt.Color(102, 102, 102));
        btnbloqueos.setText("Bloqueos");
        btnbloqueos.setBorder(null);
        btnbloqueos.setContentAreaFilled(false);
        btnbloqueos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbloqueos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnbloqueos.setMaximumSize(new java.awt.Dimension(46, 14));
        btnbloqueos.setMinimumSize(new java.awt.Dimension(46, 14));
        btnbloqueos.setPreferredSize(new java.awt.Dimension(46, 14));

        lbldesbloqueos.setBackground(new java.awt.Color(226, 226, 226));
        lbldesbloqueos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbldesbloqueos.setForeground(new java.awt.Color(0, 86, 150));
        lbldesbloqueos.setText("Desbloqueos");
        lbldesbloqueos.setOpaque(true);

        javax.swing.GroupLayout panelcontnedoropcionesLayout = new javax.swing.GroupLayout(panelcontnedoropciones);
        panelcontnedoropciones.setLayout(panelcontnedoropcionesLayout);
        panelcontnedoropcionesLayout.setHorizontalGroup(
            panelcontnedoropcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontnedoropcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcontnedoropcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnequipos, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(lbldesbloqueos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnbloqueos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panelcontnedoropcionesLayout.setVerticalGroup(
            panelcontnedoropcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontnedoropcionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldesbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panellateralLayout = new javax.swing.GroupLayout(panellateral);
        panellateral.setLayout(panellateralLayout);
        panellateralLayout.setHorizontalGroup(
            panellateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelcontnedoropciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellateralLayout.setVerticalGroup(
            panellateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellateralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelcontnedoropciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(538, Short.MAX_VALUE))
        );

        panelfondo.add(panellateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 720));

        lbltitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 86, 150));
        lbltitulo.setText("ITSON labs");
        lbltitulo.setPreferredSize(new java.awt.Dimension(40, 16));

        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);

        lbllaboratorio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbllaboratorio.setForeground(new java.awt.Color(0, 86, 150));
        lbllaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllaboratorio.setText("LAboratorio Nombre");
        lbllaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbllaboratorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblusuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusuario.setText("Usuario");
        lblusuario.setToolTipText("");
        lblusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbladmin.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladmin.setText("Admin");

        javax.swing.GroupLayout panelsuperiorLayout = new javax.swing.GroupLayout(panelsuperior);
        panelsuperior.setLayout(panelsuperiorLayout);
        panelsuperiorLayout.setHorizontalGroup(
            panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbllaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelsuperiorLayout.setVerticalGroup(
            panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addComponent(lbllaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelsuperiorLayout.createSequentialGroup()
                        .addComponent(lblusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbladmin)))
                .addContainerGap())
        );

        panelfondo.add(panelsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 40));

        jpanelcontenido.setBackground(new java.awt.Color(255, 255, 255));

        contenedorbloqueospendientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));

        lblbloqueospendientes.setBackground(new java.awt.Color(226, 226, 226));
        lblbloqueospendientes.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblbloqueospendientes.setForeground(new java.awt.Color(93, 95, 95));
        lblbloqueospendientes.setText("DESLOQUEOS PENDIENTES");

        lblnumerodebloqueos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblnumerodebloqueos.setForeground(new java.awt.Color(0, 86, 150));
        lblnumerodebloqueos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnumerodebloqueos.setText("300");

        javax.swing.GroupLayout contenedorbloqueospendientesLayout = new javax.swing.GroupLayout(contenedorbloqueospendientes);
        contenedorbloqueospendientes.setLayout(contenedorbloqueospendientesLayout);
        contenedorbloqueospendientesLayout.setHorizontalGroup(
            contenedorbloqueospendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorbloqueospendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorbloqueospendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumerodebloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbloqueospendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        contenedorbloqueospendientesLayout.setVerticalGroup(
            contenedorbloqueospendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorbloqueospendientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblbloqueospendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnumerodebloqueos)
                .addGap(37, 37, 37))
        );

        contenedordecontenido.setBackground(new java.awt.Color(255, 255, 255));

        lblmotivos.setBackground(new java.awt.Color(226, 226, 226));
        lblmotivos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblmotivos.setForeground(new java.awt.Color(93, 95, 95));
        lblmotivos.setText("Motivos");

        cbxsanciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxsanciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipos" }));
        cbxsanciones.setPreferredSize(new java.awt.Dimension(40, 15));
        cbxsanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsancionesActionPerformed(evt);
            }
        });

        lblbuscaralumno.setBackground(new java.awt.Color(226, 226, 226));
        lblbuscaralumno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblbuscaralumno.setForeground(new java.awt.Color(93, 95, 95));
        lblbuscaralumno.setText("Buscar Alumno:");

        txtbuscadoralumno.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtbuscadoralumno.setText("jTextField1");
        txtbuscadoralumno.setPreferredSize(new java.awt.Dimension(73, 15));

        btnfltrar.setText("Fltrar");
        btnfltrar.setPreferredSize(new java.awt.Dimension(73, 15));

        btnrestaurartabla.setBackground(new java.awt.Color(0, 86, 150));
        btnrestaurartabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnrestaurartabla.setForeground(new java.awt.Color(255, 255, 255));
        btnrestaurartabla.setText("Restaurar Tabla");
        btnrestaurartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurartablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        tabladesbloqueos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabladesbloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ALUMNO", "NOMBRE", "FECHA Y HORA", "MOTIVO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabladesbloqueos);

        contenedordesbloqueorapido.setBackground(new java.awt.Color(226, 226, 226));
        contenedordesbloqueorapido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        contenedordesbloqueorapido.setOpaque(false);

        lbltitulodesbloqueorapido.setBackground(new java.awt.Color(226, 226, 226));
        lbltitulodesbloqueorapido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbltitulodesbloqueorapido.setForeground(new java.awt.Color(0, 86, 150));
        lbltitulodesbloqueorapido.setText("DESBLOQUEO RAPIDO");

        lblidalumno.setBackground(new java.awt.Color(226, 226, 226));
        lblidalumno.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblidalumno.setForeground(new java.awt.Color(93, 95, 95));
        lblidalumno.setText("ID DEL ALUMNO:");

        txtidalumno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnaplicardesbloqueo.setBackground(new java.awt.Color(0, 86, 150));
        btnaplicardesbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicardesbloqueo.setForeground(new java.awt.Color(255, 255, 255));
        btnaplicardesbloqueo.setText("APLICAR DESBLOQUEO");
        btnaplicardesbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicardesbloqueoActionPerformed(evt);
            }
        });

        lblinstrucciones.setBackground(new java.awt.Color(226, 226, 226));
        lblinstrucciones.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblinstrucciones.setForeground(new java.awt.Color(93, 95, 95));
        lblinstrucciones.setText("Ingrese el ID del alumno para restaurar el acceso de forma inmediata.");

        javax.swing.GroupLayout contenedordesbloqueorapidoLayout = new javax.swing.GroupLayout(contenedordesbloqueorapido);
        contenedordesbloqueorapido.setLayout(contenedordesbloqueorapidoLayout);
        contenedordesbloqueorapidoLayout.setHorizontalGroup(
            contenedordesbloqueorapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedordesbloqueorapidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedordesbloqueorapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedordesbloqueorapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblidalumno)
                        .addComponent(txtidalumno)
                        .addComponent(lbltitulodesbloqueorapido, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnaplicardesbloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                    .addComponent(lblinstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        contenedordesbloqueorapidoLayout.setVerticalGroup(
            contenedordesbloqueorapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedordesbloqueorapidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulodesbloqueorapido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblinstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnaplicardesbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblpaginas.setBackground(new java.awt.Color(226, 226, 226));
        lblpaginas.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblpaginas.setForeground(new java.awt.Color(93, 95, 95));
        lblpaginas.setText("Mostrando 1 de 45 Paginas Bloqueos");

        btnizquierda.setText("<");

        btnderecha.setText(">");

        javax.swing.GroupLayout contenedordecontenidoLayout = new javax.swing.GroupLayout(contenedordecontenido);
        contenedordecontenido.setLayout(contenedordecontenidoLayout);
        contenedordecontenidoLayout.setHorizontalGroup(
            contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                                .addComponent(lblpaginas, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addGap(336, 336, 336)
                                .addComponent(btnizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnderecha, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addGap(43, 43, 43))
                            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                                .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxsanciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblmotivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                                                .addComponent(lblbuscaralumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(137, 137, 137))
                                            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                                                .addComponent(txtbuscadoralumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnfltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnrestaurartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contenedordesbloqueorapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenedordecontenidoLayout.setVerticalGroup(
            contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbuscaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxsanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscadoralumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnrestaurartabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenedordecontenidoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblpaginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contenedordecontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(contenedordesbloqueorapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout jpanelcontenidoLayout = new javax.swing.GroupLayout(jpanelcontenido);
        jpanelcontenido.setLayout(jpanelcontenidoLayout);
        jpanelcontenidoLayout.setHorizontalGroup(
            jpanelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedordecontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanelcontenidoLayout.createSequentialGroup()
                        .addComponent(contenedorbloqueospendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanelcontenidoLayout.setVerticalGroup(
            jpanelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorbloqueospendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenedordecontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelfondo.add(jpanelcontenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 680, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxsancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsancionesActionPerformed

    private void btnrestaurartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurartablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestaurartablaActionPerformed

    private void btnaplicardesbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicardesbloqueoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaplicardesbloqueoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnaplicardesbloqueo;
    private javax.swing.JButton btnbloqueos;
    private javax.swing.JButton btnderecha;
    private javax.swing.JButton btnequipos;
    private javax.swing.JButton btnfltrar;
    private javax.swing.JButton btnizquierda;
    private javax.swing.JButton btnrestaurartabla;
    private javax.swing.JComboBox<String> cbxsanciones;
    private javax.swing.JPanel contenedorbloqueospendientes;
    private javax.swing.JPanel contenedordecontenido;
    private javax.swing.JPanel contenedordesbloqueorapido;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelcontenido;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JLabel lblbloqueospendientes;
    private javax.swing.JLabel lblbuscaralumno;
    private javax.swing.JLabel lbldesbloqueos;
    private javax.swing.JLabel lblidalumno;
    private javax.swing.JLabel lblinstrucciones;
    private javax.swing.JLabel lbllaboratorio;
    private javax.swing.JLabel lblmotivos;
    private javax.swing.JLabel lblnumerodebloqueos;
    private javax.swing.JLabel lblpaginas;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulodesbloqueorapido;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel panelcontnedoropciones;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JPanel panellateral;
    private javax.swing.JPanel panelsuperior;
    private javax.swing.JTable tabladesbloqueos;
    private javax.swing.JTextField txtbuscadoralumno;
    private javax.swing.JTextField txtidalumno;
    // End of variables declaration//GEN-END:variables
}
