/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocio.AlumnoNegocio;
import Negocio.IAlumnoNegocio;
import Negocio.IComputadoraNegocio;
import Negocio.NegocioException;
import Persistencia.AlumnoDAO;
import Persistencia.ComputadoraDAO;
import Persistencia.ConexionBD;
import Persistencia.IAlumnoDAO;
import Persistencia.IComputadoraDAO;
import Persistencia.IConexionBD;
import dtos.AlumnoBloqueadoTablaDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author golea
 */
public class Administrador_Bloqueos extends javax.swing.JPanel {

    private int paginaActual = 1;
    private int totalPaginas = 1;
    private final int REGISTROS_POR_PAGINA = 10;
    private final IAlumnoNegocio alumnoNegocio;
    private int idLaboratorioActual = 0;
    private String nombreLaboratorio;

    /**
     * Creates new form Administrador_Bloqueos
     */
    public Administrador_Bloqueos(String nombreLab) {
        initComponents();
        if (lbllaboratorio != null) {
            lbllaboratorio.setText(nombreLab);
        }
        nombreLaboratorio = nombreLab;
        IConexionBD conexionBD = new ConexionBD();
        IComputadoraDAO computadoraDAO = new ComputadoraDAO(conexionBD);
        IAlumnoDAO alumnoDAO = new AlumnoDAO(conexionBD);
        this.alumnoNegocio = new AlumnoNegocio(new AlumnoDAO(conexionBD));
        cargarTablaAlumnosBloqueados();

    }

    public void setNombreLaboratorio(String nombre) {
        this.lbllaboratorio.setText(nombre);
    }

    public void cargarTablaAlumnosBloqueados() {
        try {
            String criterio = txtbuscar.getText().trim();
            List<AlumnoBloqueadoTablaDTO> lista = this.alumnoNegocio.obtenerAlumnosBloqueadosPaginados(
                    criterio, this.paginaActual, this.REGISTROS_POR_PAGINA
            );

            DefaultTableModel modelo = (DefaultTableModel) tabladesbloqueos.getModel();
            modelo.setRowCount(0);

            for (AlumnoBloqueadoTablaDTO alumno : lista) {
                Object[] fila = {
                    alumno.getIdAlumno(),
                    alumno.getNombre(),
                    alumno.getMotivo(),
                    alumno.getFechaBloqueo()
                };
                modelo.addRow(fila);
            }

            actualizarContadorBloqueados();
            btnpaginas.setText("Mostrando página " + paginaActual + " de " + totalPaginas);

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }

    public void actualizarContadorBloqueados() {
        try {
            String criterio = txtbuscar.getText().trim();
            // Llamamos al método recién creado en la capa de negocio
            int total = this.alumnoNegocio.obtenerTotalBloqueados(this.idLaboratorioActual, criterio);

            // Actualizamos el JLabel lblbloqueados
            lblnumbloqueados.setText(String.valueOf(total));
        } catch (NegocioException e) {
            System.err.println("Error al actualizar el contador: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        contendeorizquierdo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEqupos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        contenedorsuperior = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        lbllaboratorio = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbladmin = new javax.swing.JLabel();
        contenedorcontenido = new javax.swing.JPanel();
        contenedortotalbloqueos = new javax.swing.JPanel();
        lbltotalbloqueos = new javax.swing.JLabel();
        lblnumbloqueados = new javax.swing.JLabel();
        contenidopanel = new javax.swing.JPanel();
        lblmotivos = new javax.swing.JLabel();
        cbxmotivos = new javax.swing.JComboBox<>();
        lblbuscaralumnos = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnfiltrar = new javax.swing.JButton();
        btnrestaurartabla = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladesbloqueos = new javax.swing.JTable();
        contenedoraplicadorbloqueomanual = new javax.swing.JPanel();
        lbltituloaplicarbloqueo = new javax.swing.JLabel();
        lblidalumno = new javax.swing.JLabel();
        lblmotivo = new javax.swing.JLabel();
        txtidalumno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmotivo = new javax.swing.JTextArea();
        btnaplicarbloqueo = new javax.swing.JButton();
        btnpaginas = new javax.swing.JLabel();
        btnizquierda = new javax.swing.JButton();
        btnderecha = new javax.swing.JButton();

        panelfondo.setBackground(new java.awt.Color(255, 51, 51));
        panelfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contendeorizquierdo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));

        btnEqupos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEqupos.setForeground(new java.awt.Color(102, 102, 102));
        btnEqupos.setText("Equipos");
        btnEqupos.setBorder(null);
        btnEqupos.setContentAreaFilled(false);
        btnEqupos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEqupos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEqupos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEqupos.setInheritsPopupMenu(true);
        btnEqupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquposActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Desbloqueos");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setMaximumSize(new java.awt.Dimension(46, 14));
        jButton2.setMinimumSize(new java.awt.Dimension(46, 14));
        jButton2.setPreferredSize(new java.awt.Dimension(46, 14));

        jLabel7.setBackground(new java.awt.Color(226, 226, 226));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 86, 150));
        jLabel7.setText("Bloqueos");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEqupos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnEqupos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contendeorizquierdoLayout = new javax.swing.GroupLayout(contendeorizquierdo);
        contendeorizquierdo.setLayout(contendeorizquierdoLayout);
        contendeorizquierdoLayout.setHorizontalGroup(
            contendeorizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contendeorizquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contendeorizquierdoLayout.setVerticalGroup(
            contendeorizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contendeorizquierdoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        panelfondo.add(contendeorizquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 720));

        lbltitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 86, 150));
        lbltitulo.setText("ITSON labs");
        lbltitulo.setPreferredSize(new java.awt.Dimension(40, 16));

        btnregresar.setText("Regresar");
        btnregresar.setBorder(null);
        btnregresar.setContentAreaFilled(false);

        lbllaboratorio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbllaboratorio.setForeground(new java.awt.Color(0, 86, 150));
        lbllaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllaboratorio.setText("LAboratorio Nombre");
        lbllaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbllaboratorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblusuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusuario.setText("Usuario");
        lblusuario.setToolTipText("");
        lblusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbladmin.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladmin.setText("Admin");

        javax.swing.GroupLayout contenedorsuperiorLayout = new javax.swing.GroupLayout(contenedorsuperior);
        contenedorsuperior.setLayout(contenedorsuperiorLayout);
        contenedorsuperiorLayout.setHorizontalGroup(
            contenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorsuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbllaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        contenedorsuperiorLayout.setVerticalGroup(
            contenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnregresar)
                        .addComponent(lbllaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorsuperiorLayout.createSequentialGroup()
                        .addComponent(lblusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbladmin)))
                .addContainerGap())
        );

        panelfondo.add(contenedorsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 40));

        contenedorcontenido.setBackground(new java.awt.Color(255, 255, 255));

        contenedortotalbloqueos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));

        lbltotalbloqueos.setBackground(new java.awt.Color(226, 226, 226));
        lbltotalbloqueos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltotalbloqueos.setForeground(new java.awt.Color(93, 95, 95));
        lbltotalbloqueos.setText("TOTAL BLOQUEADOS");

        lblnumbloqueados.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblnumbloqueados.setForeground(new java.awt.Color(0, 86, 150));
        lblnumbloqueados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnumbloqueados.setText("300");

        javax.swing.GroupLayout contenedortotalbloqueosLayout = new javax.swing.GroupLayout(contenedortotalbloqueos);
        contenedortotalbloqueos.setLayout(contenedortotalbloqueosLayout);
        contenedortotalbloqueosLayout.setHorizontalGroup(
            contenedortotalbloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedortotalbloqueosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedortotalbloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumbloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltotalbloqueos))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        contenedortotalbloqueosLayout.setVerticalGroup(
            contenedortotalbloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedortotalbloqueosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnumbloqueados)
                .addGap(37, 37, 37))
        );

        contenidopanel.setBackground(new java.awt.Color(255, 255, 255));

        lblmotivos.setBackground(new java.awt.Color(226, 226, 226));
        lblmotivos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblmotivos.setForeground(new java.awt.Color(93, 95, 95));
        lblmotivos.setText("Motivos");

        cbxmotivos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxmotivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipos" }));
        cbxmotivos.setPreferredSize(new java.awt.Dimension(40, 15));
        cbxmotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmotivosActionPerformed(evt);
            }
        });

        lblbuscaralumnos.setBackground(new java.awt.Color(226, 226, 226));
        lblbuscaralumnos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblbuscaralumnos.setForeground(new java.awt.Color(93, 95, 95));
        lblbuscaralumnos.setText("Buscar Alumno:");

        txtbuscar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtbuscar.setText("jTextField1");
        txtbuscar.setPreferredSize(new java.awt.Dimension(73, 15));
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnfiltrar.setText("Fltrar");
        btnfiltrar.setPreferredSize(new java.awt.Dimension(73, 15));
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        btnrestaurartabla.setBackground(new java.awt.Color(0, 86, 150));
        btnrestaurartabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnrestaurartabla.setForeground(new java.awt.Color(255, 255, 255));
        btnrestaurartabla.setText("Restaurar Tabla");
        btnrestaurartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurartablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        tabladesbloqueos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabladesbloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ALUMNO", "NOMBRE", "MOTIVO", "FECHA Y HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabladesbloqueos);
        if (tabladesbloqueos.getColumnModel().getColumnCount() > 0) {
            tabladesbloqueos.getColumnModel().getColumn(0).setResizable(false);
            tabladesbloqueos.getColumnModel().getColumn(1).setResizable(false);
            tabladesbloqueos.getColumnModel().getColumn(2).setResizable(false);
            tabladesbloqueos.getColumnModel().getColumn(3).setResizable(false);
        }

        contenedoraplicadorbloqueomanual.setBackground(new java.awt.Color(226, 226, 226));
        contenedoraplicadorbloqueomanual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        contenedoraplicadorbloqueomanual.setOpaque(false);

        lbltituloaplicarbloqueo.setBackground(new java.awt.Color(226, 226, 226));
        lbltituloaplicarbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbltituloaplicarbloqueo.setForeground(new java.awt.Color(0, 86, 150));
        lbltituloaplicarbloqueo.setText("APLICAR BLOQUEO MANUAL:");

        lblidalumno.setBackground(new java.awt.Color(226, 226, 226));
        lblidalumno.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblidalumno.setForeground(new java.awt.Color(93, 95, 95));
        lblidalumno.setText("ID DEL ALUMNO:");

        lblmotivo.setBackground(new java.awt.Color(226, 226, 226));
        lblmotivo.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblmotivo.setForeground(new java.awt.Color(93, 95, 95));
        lblmotivo.setText("MOTIVO:");

        txtidalumno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtmotivo.setColumns(20);
        txtmotivo.setRows(5);
        jScrollPane2.setViewportView(txtmotivo);

        btnaplicarbloqueo.setBackground(new java.awt.Color(255, 51, 51));
        btnaplicarbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo.setForeground(new java.awt.Color(255, 255, 255));
        btnaplicarbloqueo.setText("APLICAR BLOQUEO");
        btnaplicarbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedoraplicadorbloqueomanualLayout = new javax.swing.GroupLayout(contenedoraplicadorbloqueomanual);
        contenedoraplicadorbloqueomanual.setLayout(contenedoraplicadorbloqueomanualLayout);
        contenedoraplicadorbloqueomanualLayout.setHorizontalGroup(
            contenedoraplicadorbloqueomanualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedoraplicadorbloqueomanualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedoraplicadorbloqueomanualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblidalumno)
                    .addComponent(lblmotivo)
                    .addComponent(txtidalumno)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(lbltituloaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        contenedoraplicadorbloqueomanualLayout.setVerticalGroup(
            contenedoraplicadorbloqueomanualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedoraplicadorbloqueomanualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltituloaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnpaginas.setBackground(new java.awt.Color(226, 226, 226));
        btnpaginas.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        btnpaginas.setForeground(new java.awt.Color(93, 95, 95));
        btnpaginas.setText("Mostrando 1 de 45 Paginas Bloqueos");

        btnizquierda.setText("<");
        btnizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizquierdaActionPerformed(evt);
            }
        });

        btnderecha.setText(">");
        btnderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidopanelLayout = new javax.swing.GroupLayout(contenidopanel);
        contenidopanel.setLayout(contenidopanelLayout);
        contenidopanelLayout.setHorizontalGroup(
            contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(contenidopanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnpaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addGroup(contenidopanelLayout.createSequentialGroup()
                            .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(contenidopanelLayout.createSequentialGroup()
                                    .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblmotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxmotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblbuscaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(contenidopanelLayout.createSequentialGroup()
                                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(contenedoraplicadorbloqueomanual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(345, 345, 345)))
                    .addGroup(contenidopanelLayout.createSequentialGroup()
                        .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnrestaurartabla)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenidopanelLayout.setVerticalGroup(
            contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidopanelLayout.createSequentialGroup()
                        .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbuscaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxmotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnrestaurartabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenidopanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnpaginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contenidopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(contenedoraplicadorbloqueomanual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout contenedorcontenidoLayout = new javax.swing.GroupLayout(contenedorcontenido);
        contenedorcontenido.setLayout(contenedorcontenidoLayout);
        contenedorcontenidoLayout.setHorizontalGroup(
            contenedorcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenidopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorcontenidoLayout.createSequentialGroup()
                        .addComponent(contenedortotalbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contenedorcontenidoLayout.setVerticalGroup(
            contenedorcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedortotalbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenidopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelfondo.add(contenedorcontenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 680, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxmotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmotivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxmotivosActionPerformed

    private void btnrestaurartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurartablaActionPerformed
        // TODO add your handling code here:
        this.txtbuscar.setText("");
        this.paginaActual = 1;
        cargarTablaAlumnosBloqueados();
    }//GEN-LAST:event_btnrestaurartablaActionPerformed

    private void btnaplicarbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueoActionPerformed
        try {
            // 1. Obtener datos de los campos
            String idTexto = txtidalumno.getText().trim();
            String motivo = txtmotivo.getText().trim();

            if (idTexto.isEmpty() || motivo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, llene el ID del alumno y el motivo.");
                return;
            }

            int idAlumno = Integer.parseInt(idTexto);

            // Asumiendo que necesitas el nombre del alumno, aquí podrías buscarlo mediante alumnoNegocio.
            // Por ahora, pasaremos "Alumno" como placeholder si no tienes una consulta rápida.
            String nombreAlumno = "Alumno " + idAlumno;

            // 2. Crear el panel de confirmación
            Confirmacion_bloqueo_alumno panelConfirmacion = new Confirmacion_bloqueo_alumno(
                    this.alumnoNegocio, idAlumno, nombreAlumno, motivo
            );

            // 3. Crear el JDialog
            javax.swing.JDialog dialog = new javax.swing.JDialog((javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), "Confirmar Bloqueo", true);
            dialog.getContentPane().add(panelConfirmacion);
            panelConfirmacion.setDialogPadre(dialog); // Pasamos la referencia para que el panel pueda cerrarlo
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // 4. Actualizar tabla después de cerrar el diálogo
            cargarTablaAlumnosBloqueados();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del alumno debe ser un número válido.");
        }
    }//GEN-LAST:event_btnaplicarbloqueoActionPerformed

    private void btnizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizquierdaActionPerformed
        // TODO add your handling code here:
        if (this.paginaActual > 1) {
            this.paginaActual--;
            cargarTablaAlumnosBloqueados();
        }
    }//GEN-LAST:event_btnizquierdaActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        // TODO add your handling code here:
        this.paginaActual = 1;
        cargarTablaAlumnosBloqueados();


    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btnderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderechaActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            cargarTablaAlumnosBloqueados();
        }
    }//GEN-LAST:event_btnderechaActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnEquposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquposActionPerformed
        // TODO add your handling code here:

        Administrador_Equipos ventanaEquipos = new Administrador_Equipos();

        // 2. Hacer visible la nueva ventana
        ventanaEquipos.setVisible(true);

        // 3. Opcional: Cerrar la ventana actual si es un JFrame
        // Si Administrador_Bloqueos vive dentro de un JFrame, puedes obtenerlo así:
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win != null) {
            win.dispose(); // Esto cierra la ventana donde está contenido este JPanel
        }
    }//GEN-LAST:event_btnEquposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEqupos;
    private javax.swing.JButton btnaplicarbloqueo;
    private javax.swing.JButton btnderecha;
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnizquierda;
    private javax.swing.JLabel btnpaginas;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnrestaurartabla;
    private javax.swing.JComboBox<String> cbxmotivos;
    private javax.swing.JPanel contendeorizquierdo;
    private javax.swing.JPanel contenedoraplicadorbloqueomanual;
    private javax.swing.JPanel contenedorcontenido;
    private javax.swing.JPanel contenedorsuperior;
    private javax.swing.JPanel contenedortotalbloqueos;
    private javax.swing.JPanel contenidopanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JLabel lblbuscaralumnos;
    private javax.swing.JLabel lblidalumno;
    private javax.swing.JLabel lbllaboratorio;
    private javax.swing.JLabel lblmotivo;
    private javax.swing.JLabel lblmotivos;
    private javax.swing.JLabel lblnumbloqueados;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltituloaplicarbloqueo;
    private javax.swing.JLabel lbltotalbloqueos;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JTable tabladesbloqueos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtidalumno;
    private javax.swing.JTextArea txtmotivo;
    // End of variables declaration//GEN-END:variables
}
