/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocio.NegocioException;
import dtos.BloqueoEquipoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author golea
 */
public class Confirmacion_Bloqueo_Equipos extends javax.swing.JPanel {

    private Administrador_Equipos ventanaPrincipal;
    private javax.swing.JDialog dialogoContenedor;

   
    public Confirmacion_Bloqueo_Equipos(Administrador_Equipos principal, javax.swing.JDialog dialogo) {
        this.ventanaPrincipal = principal;
        this.dialogoContenedor = dialogo;
        initComponents();
        txtNumeromaquina.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeromaquina = new javax.swing.JTextField();
        btnaplicarbloqueo = new javax.swing.JButton();
        btnaplicarbloqueo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        txtNumeromaquina.setText("jTextField1");
        txtNumeromaquina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 95, 95), 2));
        txtNumeromaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeromaquinaActionPerformed(evt);
            }
        });

        btnaplicarbloqueo.setBackground(new java.awt.Color(255, 51, 51));
        btnaplicarbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo.setForeground(new java.awt.Color(255, 255, 255));
        btnaplicarbloqueo.setText("Confirmar Bloqueo");
        btnaplicarbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueoActionPerformed(evt);
            }
        });

        btnaplicarbloqueo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo1.setForeground(new java.awt.Color(93, 95, 95));
        btnaplicarbloqueo1.setText("Cancelar");
        btnaplicarbloqueo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(93, 95, 95), 2, true));
        btnaplicarbloqueo1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar bloqueo de Equipo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 95, 95));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Para proceder con el bloqueo, por favor ingrese");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 95, 95));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("el número de máquina correspondiente.");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 95, 95));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("NUMERO DE MAQUINA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnaplicarbloqueo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeromaquina)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeromaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeromaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeromaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeromaquinaActionPerformed

    private void btnaplicarbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueoActionPerformed
        String numeroMaquinaStr = txtNumeromaquina.getText().trim();

        if (numeroMaquinaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el número de máquina.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int numeroMaquina = Integer.parseInt(numeroMaquinaStr);

            dtos.BloqueoEquipoDTO bloqueoDTO = new dtos.BloqueoEquipoDTO();
            bloqueoDTO.setNumeroMaquina(numeroMaquina);
            bloqueoDTO.setIdLaboratorioActual(ventanaPrincipal.getIdLaboratorioActual());

            boolean exito = ventanaPrincipal.getComputadoraNegocio().bloquearEquipoPorNumero(bloqueoDTO);

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "El equipo número " + numeroMaquina + " ha sido Bloqueado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                if (dialogoContenedor != null) {
                    dialogoContenedor.dispose();
                }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de máquina debe ser un valor numérico.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Negocio.NegocioException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Validación de Bloqueo", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnaplicarbloqueo1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (dialogoContenedor != null) {
            dialogoContenedor.dispose();
        }
    }//GEN-LAST:event_btnaplicarbloqueoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaplicarbloqueo;
    private javax.swing.JButton btnaplicarbloqueo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNumeromaquina;
    // End of variables declaration//GEN-END:variables
}
