/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocio.IAlumnoNegocio;
import dtos.AlumnoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author golea
 */
public class Confirmacion_Debloqueo_alumno extends javax.swing.JPanel {

    private IAlumnoNegocio alumnoNegocio;
    private int idAlumno;
    private javax.swing.JDialog dialogPadre;

    /**
     * Creates new form Confirmacion_Debloqueo_alumno
     */
    public Confirmacion_Debloqueo_alumno(IAlumnoNegocio negocio, int idAlumno) {
        initComponents();
        this.alumnoNegocio = negocio;
        this.idAlumno = idAlumno;
        buscarYConfigurarMensaje();
    }

    private void buscarYConfigurarMensaje() {
        try {
            // Asumiendo que tienes un método para obtener el alumno por ID
            AlumnoDTO alumno = alumnoNegocio.obtenerAlumnoPorId(idAlumno);
            String mensaje = "¿Está seguro de que desea restaurar el acceso al alumno " + alumno.getNombre()
                    + " con ID " + idAlumno + "?\n\nEsta acción permitirá al estudiante utilizar los laboratorios de nuevo.";
            jTextArea1.setText(mensaje);
        } catch (Exception e) {
            jTextArea1.setText("Error al cargar datos del alumno.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnaplicarbloqueo = new javax.swing.JButton();
        btnaplicarbloqueo1 = new javax.swing.JButton();

        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("¿Está seguro de que desea restaurar el acceso al alumno Nomnre del alumno y su id? Esta acción permitirá al estudiante utilizar los laboratorios de nuevo.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTextArea1);

        btnaplicarbloqueo.setBackground(new java.awt.Color(0, 86, 150));
        btnaplicarbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo.setForeground(new java.awt.Color(255, 255, 255));
        btnaplicarbloqueo.setText("Confirmar Desbloqueo");
        btnaplicarbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueoActionPerformed(evt);
            }
        });

        btnaplicarbloqueo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo1.setForeground(new java.awt.Color(93, 95, 95));
        btnaplicarbloqueo1.setText("Cancelar");
        btnaplicarbloqueo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(93, 95, 95), 2, true));
        btnaplicarbloqueo1.setOpaque(true);
        btnaplicarbloqueo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaplicarbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueoActionPerformed
        // TODO add your handling code here:
        try {
            alumnoNegocio.eliminarBloqueo(idAlumno);
            JOptionPane.showMessageDialog(this, "Alumno desbloqueado exitosamente.");
            if (dialogPadre != null) {
                dialogPadre.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnaplicarbloqueoActionPerformed

    private void btnaplicarbloqueo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueo1ActionPerformed
        // TODO add your handling code here:
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win != null) {
            win.dispose();
        }
    }//GEN-LAST:event_btnaplicarbloqueo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaplicarbloqueo;
    private javax.swing.JButton btnaplicarbloqueo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
