/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocio.IAlumnoNegocio;
import dtos.BloqueoAlumnoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author golea
 */
public class Confirmacion_bloqueo_alumno extends javax.swing.JPanel {

    private IAlumnoNegocio alumnoNegocio;
    private int idAlumno;
    private String motivo;
    private javax.swing.JDialog dialogPadre;

    /**
     * Creates new form Confirmacion_bloqueo_alumno
     */
    public Confirmacion_bloqueo_alumno(IAlumnoNegocio negocio, int idAlumno, String nombreAlumno, String motivo) {
        initComponents();
        this.alumnoNegocio = negocio;
        this.idAlumno = idAlumno;
        this.motivo = motivo;

        String mensaje = "¿Está seguro de que desea aplicar un bloqueo al alumno " + nombreAlumno
                + " por el motivo: " + motivo + "?\n\n"
                + "El estudiante no podrá utilizar ningún equipo de laboratorio hasta que el bloqueo sea removido.";
        jTextArea1.setText(mensaje);
    }

    public void setDialogPadre(javax.swing.JDialog dialog) {
        this.dialogPadre = dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnaplicarbloqueo = new javax.swing.JButton();
        btnaplicarbloqueo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar bloqueo de Equipo");

        btnaplicarbloqueo.setBackground(new java.awt.Color(255, 51, 51));
        btnaplicarbloqueo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo.setForeground(new java.awt.Color(255, 255, 255));
        btnaplicarbloqueo.setText("Confirmar Bloqueo");
        btnaplicarbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueoActionPerformed(evt);
            }
        });

        btnaplicarbloqueo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnaplicarbloqueo1.setForeground(new java.awt.Color(93, 95, 95));
        btnaplicarbloqueo1.setText("Cancelar");
        btnaplicarbloqueo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(93, 95, 95), 2, true));
        btnaplicarbloqueo1.setOpaque(true);
        btnaplicarbloqueo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarbloqueo1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaplicarbloqueo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaplicarbloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaplicarbloqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaplicarbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueoActionPerformed
        // TODO add your handling code here:
        try {
            // Asegúrate de que idAlumno se pase como String desde la pantalla anterior
            // Si tienes el valor numérico, conviértelo aquí:
            String idFormateado = String.format("%010d", this.idAlumno);

            BloqueoAlumnoDTO dto = new BloqueoAlumnoDTO(idFormateado, this.motivo);
            alumnoNegocio.bloquearAlumno(dto);

            JOptionPane.showMessageDialog(this, "Alumno bloqueado exitosamente.");
            if (dialogPadre != null) {
                dialogPadre.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnaplicarbloqueoActionPerformed

    private void btnaplicarbloqueo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarbloqueo1ActionPerformed
        // TODO add your handling code here:
        if (dialogPadre != null) {
            dialogPadre.dispose();
        }
    }//GEN-LAST:event_btnaplicarbloqueo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaplicarbloqueo;
    private javax.swing.JButton btnaplicarbloqueo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
