/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class PantallaInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicioSesion
     */
    public PantallaInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contendedorfondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbliniciarsesiontitulo = new javax.swing.JLabel();
        lblinstrucciones = new javax.swing.JLabel();
        lblalumno = new javax.swing.JLabel();
        lbltextocontraseña = new javax.swing.JLabel();
        txtalumnoid = new javax.swing.JTextField();
        txtinnsertarContraseña = new javax.swing.JTextField();
        btningresar = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        panelcontenedorsuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contendedorfondo.setBackground(new java.awt.Color(255, 255, 255));
        contendedorfondo.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        lbliniciarsesiontitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbliniciarsesiontitulo.setForeground(new java.awt.Color(0, 86, 150));
        lbliniciarsesiontitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbliniciarsesiontitulo.setText("Iniciar Sesión");

        lblinstrucciones.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblinstrucciones.setForeground(new java.awt.Color(102, 102, 102));
        lblinstrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinstrucciones.setText("Ingresa tus datos del prestamo");

        lblalumno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblalumno.setForeground(new java.awt.Color(102, 102, 102));
        lblalumno.setText("ID DEL ALUMNO:");

        lbltextocontraseña.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltextocontraseña.setForeground(new java.awt.Color(102, 102, 102));
        lbltextocontraseña.setText("CONTRASEÑA:");

        txtalumnoid.setBackground(new java.awt.Color(240, 241, 241));
        txtalumnoid.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtalumnoid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalumnoidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtalumnoidFocusLost(evt);
            }
        });

        txtinnsertarContraseña.setBackground(new java.awt.Color(240, 241, 241));
        txtinnsertarContraseña.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtinnsertarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusLost(evt);
            }
        });

        btningresar.setBackground(new java.awt.Color(0, 72, 128));
        btningresar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btningresar.setForeground(new java.awt.Color(255, 255, 255));
        btningresar.setText("INGRESAR");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblinstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbliniciarsesiontitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separador)
                    .addComponent(txtalumnoid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtinnsertarContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbltextocontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(lblalumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(127, 127, 127))
                    .addComponent(btningresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbliniciarsesiontitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinstrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblalumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtalumnoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lbltextocontraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtinnsertarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 80, 109, 0);
        contendedorfondo.add(jPanel2, gridBagConstraints);

        panelcontenedorsuperior.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 86, 150));
        titulo.setText("ITSON labs");
        titulo.setPreferredSize(new java.awt.Dimension(40, 16));

        javax.swing.GroupLayout panelcontenedorsuperiorLayout = new javax.swing.GroupLayout(panelcontenedorsuperior);
        panelcontenedorsuperior.setLayout(panelcontenedorsuperiorLayout);
        panelcontenedorsuperiorLayout.setHorizontalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(304, 304, 304))
        );
        panelcontenedorsuperiorLayout.setVerticalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        contendedorfondo.add(panelcontenedorsuperior, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contendedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contendedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalumnoidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalumnoidFocusGained
        // TODO add your handling code here:
        if (txtalumnoid.getText().equals("Ingrese su Contraseña")) {
            txtalumnoid.setText("");
            txtalumnoid.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtalumnoidFocusGained

    private void txtalumnoidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalumnoidFocusLost
        // TODO add your handling code here:
        if (txtalumnoid.getText().isEmpty()) {
            txtalumnoid.setText("Ingrese su Contraseña");
            txtalumnoid.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtalumnoidFocusLost

    private void txtinnsertarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinnsertarContraseñaFocusGained

    private void txtinnsertarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinnsertarContraseñaFocusLost

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btningresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JPanel contendedorfondo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblalumno;
    private javax.swing.JLabel lbliniciarsesiontitulo;
    private javax.swing.JLabel lblinstrucciones;
    private javax.swing.JLabel lbltextocontraseña;
    private javax.swing.JPanel panelcontenedorsuperior;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtalumnoid;
    private javax.swing.JTextField txtinnsertarContraseña;
    // End of variables declaration//GEN-END:variables
}
