/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class Pantalla_Apartado extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla_Apartado
     */
    public Pantalla_Apartado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorfondo = new javax.swing.JPanel();
        panelcontenedorsuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblequipo = new javax.swing.JLabel();
        lblubicacion_centro_computo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbldetallesreserva = new javax.swing.JLabel();
        lbldetallesdelamamaquina3 = new javax.swing.JLabel();
        lblnumerodemaquina = new javax.swing.JLabel();
        lbldetallesdelamamaquina4 = new javax.swing.JLabel();
        lblidusuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbltiemporestante = new javax.swing.JLabel();
        lbltiempo = new javax.swing.JLabel();
        lblsesionenespera = new javax.swing.JLabel();
        btnregresaraliinicio = new javax.swing.JButton();

        contenedorfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelcontenedorsuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelcontenedorsuperior.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 86, 150));
        titulo.setText("ITSON labs");
        titulo.setPreferredSize(new java.awt.Dimension(40, 16));

        javax.swing.GroupLayout panelcontenedorsuperiorLayout = new javax.swing.GroupLayout(panelcontenedorsuperior);
        panelcontenedorsuperior.setLayout(panelcontenedorsuperiorLayout);
        panelcontenedorsuperiorLayout.setHorizontalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(304, 304, 304))
        );
        panelcontenedorsuperiorLayout.setVerticalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        contenedorfondo.add(panelcontenedorsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblequipo.setForeground(new java.awt.Color(0, 86, 150));
        lblequipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblequipo.setText("Computadora Reservada Con Exito");

        lblubicacion_centro_computo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblubicacion_centro_computo.setForeground(new java.awt.Color(102, 102, 102));
        lblubicacion_centro_computo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblubicacion_centro_computo.setText("Su sesión ha comenzado. Por favor, diríjase a su estación de trabajo.");
        lblubicacion_centro_computo.setToolTipText("");

        lbldetallesreserva.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbldetallesreserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldetallesreserva.setText("Detalles de Reserva");

        lbldetallesdelamamaquina3.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbldetallesdelamamaquina3.setForeground(new java.awt.Color(102, 102, 102));
        lbldetallesdelamamaquina3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldetallesdelamamaquina3.setText("Numero de la Maquina");

        lblnumerodemaquina.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblnumerodemaquina.setForeground(new java.awt.Color(102, 102, 102));
        lblnumerodemaquina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnumerodemaquina.setText("41");

        lbldetallesdelamamaquina4.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbldetallesdelamamaquina4.setForeground(new java.awt.Color(102, 102, 102));
        lbldetallesdelamamaquina4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldetallesdelamamaquina4.setText("Usuario");

        lblidusuario.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblidusuario.setForeground(new java.awt.Color(102, 102, 102));
        lblidusuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblidusuario.setText("00000235419");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbldetallesreserva, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblnumerodemaquina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldetallesdelamamaquina4)
                            .addComponent(lblidusuario)
                            .addComponent(lbldetallesdelamamaquina3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldetallesreserva)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldetallesdelamamaquina3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnumerodemaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldetallesdelamamaquina4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblidusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbltiemporestante.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltiemporestante.setForeground(new java.awt.Color(102, 102, 102));
        lbltiemporestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltiemporestante.setText("TIEMPO RESTANTE");

        lbltiempo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbltiempo.setForeground(new java.awt.Color(0, 86, 150));
        lbltiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltiempo.setText("1:00:00");

        lblsesionenespera.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblsesionenespera.setForeground(new java.awt.Color(102, 102, 102));
        lblsesionenespera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsesionenespera.setText("Sesion En Espera");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbltiemporestante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbltiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsesionenespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltiemporestante)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsesionenespera)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnregresaraliinicio.setBackground(new java.awt.Color(0, 72, 128));
        btnregresaraliinicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnregresaraliinicio.setForeground(new java.awt.Color(255, 255, 255));
        btnregresaraliinicio.setText("Regresar al Inicio");
        btnregresaraliinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresaraliinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblubicacion_centro_computo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnregresaraliinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblequipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblubicacion_centro_computo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnregresaraliinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        contenedorfondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresaraliinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresaraliinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresaraliinicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresaraliinicio;
    private javax.swing.JPanel contenedorfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbldetallesdelamamaquina3;
    private javax.swing.JLabel lbldetallesdelamamaquina4;
    private javax.swing.JLabel lbldetallesreserva;
    private javax.swing.JLabel lblequipo;
    private javax.swing.JLabel lblidusuario;
    private javax.swing.JLabel lblnumerodemaquina;
    private javax.swing.JLabel lblsesionenespera;
    private javax.swing.JLabel lbltiempo;
    private javax.swing.JLabel lbltiemporestante;
    private javax.swing.JLabel lblubicacion_centro_computo;
    private javax.swing.JPanel panelcontenedorsuperior;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
