/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class pantalla_Selecciondeequipo extends javax.swing.JPanel {

    /**
     * Creates new form pantalla_Selecciondeequipo
     */
    public pantalla_Selecciondeequipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorfondo = new javax.swing.JPanel();
        panelcontenedorsuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        lblTitulogestiondelaboratorios = new javax.swing.JLabel();
        lblonumerocupados = new javax.swing.JLabel();
        lblnumerodisponibles = new javax.swing.JLabel();
        lbllaboratorioseleccionado = new javax.swing.JLabel();
        lblnombredelcentro = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panellaboratorio = new javax.swing.JPanel();
        lblinformacionlaboratorio = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblinformacionlaboratorio2 = new javax.swing.JLabel();
        lblinformacionlaboratorio3 = new javax.swing.JLabel();
        contenedormaquina = new javax.swing.JPanel();
        lbldetallesdelamamaquina = new javax.swing.JLabel();
        lbltitulonumeroequipo = new javax.swing.JLabel();
        lblnumerodeequipo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbliptitulo = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        contenedorsoftware = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LISTADESOFTWARES = new javax.swing.JList<>();
        btnApartarEquipo = new javax.swing.JButton();
        LBLtitulosoftware = new javax.swing.JLabel();
        contenedortitulocomputadoras = new javax.swing.JPanel();
        lbltodaslascomputadoras = new javax.swing.JLabel();
        Contenedordecomputadoras = new javax.swing.JPanel();

        contenedorfondo.setBackground(new java.awt.Color(255, 255, 51));
        contenedorfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelcontenedorsuperior.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 86, 150));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("ITSON labs");
        titulo.setPreferredSize(new java.awt.Dimension(40, 16));

        lblTitulogestiondelaboratorios.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblTitulogestiondelaboratorios.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulogestiondelaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulogestiondelaboratorios.setText("Gestion de laboratorios");

        lblonumerocupados.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblonumerocupados.setForeground(new java.awt.Color(102, 102, 102));
        lblonumerocupados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblonumerocupados.setText("10 Ocupados");

        lblnumerodisponibles.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblnumerodisponibles.setForeground(new java.awt.Color(102, 102, 102));
        lblnumerodisponibles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnumerodisponibles.setText("10 Disponibles");

        lbllaboratorioseleccionado.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbllaboratorioseleccionado.setForeground(new java.awt.Color(102, 102, 102));
        lbllaboratorioseleccionado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllaboratorioseleccionado.setText("LABORATORIO SELECCIONADO");

        lblnombredelcentro.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblnombredelcentro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnombredelcentro.setText("nOMBREDELCENTRO");

        btnregresar.setText("Regresar");
        btnregresar.setBorder(null);
        btnregresar.setContentAreaFilled(false);
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcontenedorsuperiorLayout = new javax.swing.GroupLayout(panelcontenedorsuperior);
        panelcontenedorsuperior.setLayout(panelcontenedorsuperiorLayout);
        panelcontenedorsuperiorLayout.setHorizontalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                        .addComponent(lblTitulogestiondelaboratorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnombredelcentro))
                    .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbllaboratorioseleccionado)))
                .addGap(38, 38, 38)
                .addComponent(lblnumerodisponibles)
                .addGap(32, 32, 32)
                .addComponent(lblonumerocupados)
                .addContainerGap())
        );
        panelcontenedorsuperiorLayout.setVerticalGroup(
            panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulogestiondelaboratorios)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcontenedorsuperiorLayout.createSequentialGroup()
                .addComponent(lbllaboratorioseleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcontenedorsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblonumerocupados)
                        .addComponent(lblnumerodisponibles))
                    .addGroup(panelcontenedorsuperiorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblnombredelcentro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        contenedorfondo.add(panelcontenedorsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panellaboratorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        lblinformacionlaboratorio.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblinformacionlaboratorio.setForeground(new java.awt.Color(102, 102, 102));
        lblinformacionlaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblinformacionlaboratorio.setText("INFORMACION DEL LABORATORIO");

        lblidentificacion.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblidentificacion.setForeground(new java.awt.Color(102, 102, 102));
        lblidentificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblidentificacion.setText("Identificacion del Aula");

        titulo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 86, 150));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo1.setText("ITSON labs");
        titulo1.setPreferredSize(new java.awt.Dimension(40, 16));

        lblinformacionlaboratorio2.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblinformacionlaboratorio2.setForeground(new java.awt.Color(102, 102, 102));
        lblinformacionlaboratorio2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblinformacionlaboratorio2.setText("Usuario:");

        lblinformacionlaboratorio3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblinformacionlaboratorio3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblinformacionlaboratorio3.setText("Nombre del estudiante");

        javax.swing.GroupLayout panellaboratorioLayout = new javax.swing.GroupLayout(panellaboratorio);
        panellaboratorio.setLayout(panellaboratorioLayout);
        panellaboratorioLayout.setHorizontalGroup(
            panellaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellaboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblinformacionlaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblidentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblinformacionlaboratorio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblinformacionlaboratorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panellaboratorioLayout.setVerticalGroup(
            panellaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellaboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblinformacionlaboratorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblidentificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinformacionlaboratorio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinformacionlaboratorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedormaquina.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        lbldetallesdelamamaquina.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbldetallesdelamamaquina.setForeground(new java.awt.Color(102, 102, 102));
        lbldetallesdelamamaquina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldetallesdelamamaquina.setText("DETALLES DE LA MAQUINA");

        lbltitulonumeroequipo.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbltitulonumeroequipo.setForeground(new java.awt.Color(102, 102, 102));
        lbltitulonumeroequipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulonumeroequipo.setText("Numero de Equipo:");

        lblnumerodeequipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblnumerodeequipo.setForeground(new java.awt.Color(0, 86, 150));
        lblnumerodeequipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnumerodeequipo.setText("35");
        lblnumerodeequipo.setPreferredSize(new java.awt.Dimension(40, 16));

        lbliptitulo.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lbliptitulo.setForeground(new java.awt.Color(102, 102, 102));
        lbliptitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbliptitulo.setText("Dirreccion IP:");

        lblip.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblip.setText("192.251.64.5");

        javax.swing.GroupLayout contenedormaquinaLayout = new javax.swing.GroupLayout(contenedormaquina);
        contenedormaquina.setLayout(contenedormaquinaLayout);
        contenedormaquinaLayout.setHorizontalGroup(
            contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedormaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldetallesdelamamaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(lblnumerodeequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(contenedormaquinaLayout.createSequentialGroup()
                        .addGroup(contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltitulonumeroequipo)
                            .addComponent(lbliptitulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedormaquinaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        contenedormaquinaLayout.setVerticalGroup(
            contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedormaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbldetallesdelamamaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulonumeroequipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnumerodeequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbliptitulo)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(contenedormaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedormaquinaLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(lblip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        contenedorsoftware.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        LISTADESOFTWARES.setBorder(null);
        LISTADESOFTWARES.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LISTADESOFTWARES.setOpaque(false);
        jScrollPane1.setViewportView(LISTADESOFTWARES);

        btnApartarEquipo.setBackground(new java.awt.Color(0, 72, 128));
        btnApartarEquipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnApartarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        btnApartarEquipo.setText("Apartar Equipo");
        btnApartarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartarEquipoActionPerformed(evt);
            }
        });

        LBLtitulosoftware.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        LBLtitulosoftware.setForeground(new java.awt.Color(102, 102, 102));
        LBLtitulosoftware.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLtitulosoftware.setText("SOFTWARE INSTALADO");

        javax.swing.GroupLayout contenedorsoftwareLayout = new javax.swing.GroupLayout(contenedorsoftware);
        contenedorsoftware.setLayout(contenedorsoftwareLayout);
        contenedorsoftwareLayout.setHorizontalGroup(
            contenedorsoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorsoftwareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorsoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApartarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(LBLtitulosoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contenedorsoftwareLayout.setVerticalGroup(
            contenedorsoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorsoftwareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLtitulosoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApartarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panellaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedormaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorsoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panellaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedormaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorsoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        contenedorfondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 630));

        lbltodaslascomputadoras.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbltodaslascomputadoras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltodaslascomputadoras.setText("Todas las computadoras");

        javax.swing.GroupLayout contenedortitulocomputadorasLayout = new javax.swing.GroupLayout(contenedortitulocomputadoras);
        contenedortitulocomputadoras.setLayout(contenedortitulocomputadorasLayout);
        contenedortitulocomputadorasLayout.setHorizontalGroup(
            contenedortitulocomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedortitulocomputadorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltodaslascomputadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        contenedortitulocomputadorasLayout.setVerticalGroup(
            contenedortitulocomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedortitulocomputadorasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbltodaslascomputadoras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedorfondo.add(contenedortitulocomputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 670, 50));

        javax.swing.GroupLayout ContenedordecomputadorasLayout = new javax.swing.GroupLayout(Contenedordecomputadoras);
        Contenedordecomputadoras.setLayout(ContenedordecomputadorasLayout);
        ContenedordecomputadorasLayout.setHorizontalGroup(
            ContenedordecomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        ContenedordecomputadorasLayout.setVerticalGroup(
            ContenedordecomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        contenedorfondo.add(Contenedordecomputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 670, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnApartarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartarEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApartarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedordecomputadoras;
    private javax.swing.JLabel LBLtitulosoftware;
    private javax.swing.JList<String> LISTADESOFTWARES;
    private javax.swing.JButton btnApartarEquipo;
    private javax.swing.JButton btnregresar;
    private javax.swing.JPanel contenedorfondo;
    private javax.swing.JPanel contenedormaquina;
    private javax.swing.JPanel contenedorsoftware;
    private javax.swing.JPanel contenedortitulocomputadoras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitulogestiondelaboratorios;
    private javax.swing.JLabel lbldetallesdelamamaquina;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JLabel lblinformacionlaboratorio;
    private javax.swing.JLabel lblinformacionlaboratorio2;
    private javax.swing.JLabel lblinformacionlaboratorio3;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbliptitulo;
    private javax.swing.JLabel lbllaboratorioseleccionado;
    private javax.swing.JLabel lblnombredelcentro;
    private javax.swing.JLabel lblnumerodeequipo;
    private javax.swing.JLabel lblnumerodisponibles;
    private javax.swing.JLabel lblonumerocupados;
    private javax.swing.JLabel lbltitulonumeroequipo;
    private javax.swing.JLabel lbltodaslascomputadoras;
    private javax.swing.JPanel panelcontenedorsuperior;
    private javax.swing.JPanel panellaboratorio;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
