/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class PantallaBloqueoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaBloqueoPrincipal
     */
    public PantallaBloqueoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        fondo = new javax.swing.JPanel();
        bginiciosesion = new javax.swing.JPanel();
        lblequipo = new javax.swing.JLabel();
        lbl_numerodequipo = new javax.swing.JLabel();
        lblubicacion_centro_computo = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        panelcontenedorestadoyalumno = new javax.swing.JPanel();
        lbltextoalumno = new javax.swing.JLabel();
        lblTextoestadoactual = new javax.swing.JLabel();
        lblEstadoActual = new javax.swing.JLabel();
        lblTipodeReserva = new javax.swing.JLabel();
        lbltextocontraseña = new javax.swing.JLabel();
        txtinnsertarContraseña = new javax.swing.JTextField();
        btnDesbloquear = new javax.swing.JButton();
        lblTextoVerificacion = new javax.swing.JLabel();
        lblTiempoRegresivo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fondo.setBackground(new java.awt.Color(242, 245, 248));
        fondo.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(fondo, gridBagConstraints);

        bginiciosesion.setLayout(new java.awt.GridBagLayout());

        lblequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblequipo.setForeground(new java.awt.Color(0, 86, 150));
        lblequipo.setText("Equipo #");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 17, 0, 0);
        bginiciosesion.add(lblequipo, gridBagConstraints);

        lbl_numerodequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_numerodequipo.setForeground(new java.awt.Color(0, 86, 150));
        lbl_numerodequipo.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 0, 0);
        bginiciosesion.add(lbl_numerodequipo, gridBagConstraints);

        lblubicacion_centro_computo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblubicacion_centro_computo.setForeground(new java.awt.Color(102, 102, 102));
        lblubicacion_centro_computo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblubicacion_centro_computo.setText("Centro de Cómputo: Laboratorio Biblioteca");
        lblubicacion_centro_computo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 0, 0);
        bginiciosesion.add(lblubicacion_centro_computo, gridBagConstraints);

        lblip.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblip.setForeground(new java.awt.Color(102, 102, 102));
        lblip.setText("IP: 192.168.1.115");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        bginiciosesion.add(lblip, gridBagConstraints);

        panelcontenedorestadoyalumno.setBackground(new java.awt.Color(210, 228, 255));
        panelcontenedorestadoyalumno.setForeground(new java.awt.Color(0, 86, 150));
        panelcontenedorestadoyalumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltextoalumno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltextoalumno.setForeground(new java.awt.Color(0, 86, 150));
        lbltextoalumno.setText("Alumno");
        panelcontenedorestadoyalumno.add(lbltextoalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        lblTextoestadoactual.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblTextoestadoactual.setForeground(new java.awt.Color(0, 86, 150));
        lblTextoestadoactual.setText("Estado Actual");
        panelcontenedorestadoyalumno.add(lblTextoestadoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblEstadoActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstadoActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstadoActual.setText("Dsponible");
        panelcontenedorestadoyalumno.add(lblEstadoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        lblTipodeReserva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTipodeReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipodeReserva.setText("Sin Reservar");
        panelcontenedorestadoyalumno.add(lblTipodeReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 30, 130, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 20, 0, 10);
        bginiciosesion.add(panelcontenedorestadoyalumno, gridBagConstraints);

        lbltextocontraseña.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbltextocontraseña.setForeground(new java.awt.Color(102, 102, 102));
        lbltextocontraseña.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        bginiciosesion.add(lbltextocontraseña, gridBagConstraints);

        txtinnsertarContraseña.setBackground(new java.awt.Color(240, 241, 241));
        txtinnsertarContraseña.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtinnsertarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 0, 10);
        bginiciosesion.add(txtinnsertarContraseña, gridBagConstraints);

        btnDesbloquear.setBackground(new java.awt.Color(0, 72, 128));
        btnDesbloquear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDesbloquear.setForeground(new java.awt.Color(255, 255, 255));
        btnDesbloquear.setText("Desbloquear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 10);
        bginiciosesion.add(btnDesbloquear, gridBagConstraints);

        lblTextoVerificacion.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblTextoVerificacion.setForeground(new java.awt.Color(102, 102, 102));
        lblTextoVerificacion.setText("Verificando estado en:");
        lblTextoVerificacion.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 0);
        bginiciosesion.add(lblTextoVerificacion, gridBagConstraints);

        lblTiempoRegresivo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblTiempoRegresivo.setForeground(new java.awt.Color(102, 102, 102));
        lblTiempoRegresivo.setText("30");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        bginiciosesion.add(lblTiempoRegresivo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        getContentPane().add(bginiciosesion, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinnsertarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusGained
        // TODO add your handling code here:
        if (txtinnsertarContraseña.getText().equals("Ingrese su Contraseña")) {
            txtinnsertarContraseña.setText("");
            txtinnsertarContraseña.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtinnsertarContraseñaFocusGained

    private void txtinnsertarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusLost
        // TODO add your handling code here:
        if (txtinnsertarContraseña.getText().isEmpty()) {
            txtinnsertarContraseña.setText("Ingrese su Contraseña");
            txtinnsertarContraseña.setForeground(new java.awt.Color(153, 153, 153)); 
        }
    }//GEN-LAST:event_txtinnsertarContraseñaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBloqueoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bginiciosesion;
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblEstadoActual;
    private javax.swing.JLabel lblTextoVerificacion;
    private javax.swing.JLabel lblTextoestadoactual;
    private javax.swing.JLabel lblTiempoRegresivo;
    private javax.swing.JLabel lblTipodeReserva;
    private javax.swing.JLabel lbl_numerodequipo;
    private javax.swing.JLabel lblequipo;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbltextoalumno;
    private javax.swing.JLabel lbltextocontraseña;
    private javax.swing.JLabel lblubicacion_centro_computo;
    private javax.swing.JPanel panelcontenedorestadoyalumno;
    private javax.swing.JTextField txtinnsertarContraseña;
    // End of variables declaration//GEN-END:variables
}
