/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class Pantalla_Bloqueo_Alumno extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla_Bloqueo_Alumno
     */
    public Pantalla_Bloqueo_Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        bginiciosesion = new javax.swing.JPanel();
        lblequipo = new javax.swing.JLabel();
        lbl_numerodequipo = new javax.swing.JLabel();
        lblubicacion_centro_computo = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        panelContendedorestadoyalumno = new javax.swing.JPanel();
        lbltextoalumno = new javax.swing.JLabel();
        lblTextoestadoactual = new javax.swing.JLabel();
        lblEstadoActual = new javax.swing.JLabel();
        lblNombredelAlumno = new javax.swing.JLabel();
        lbltextocontraseña = new javax.swing.JLabel();
        txtinnsertarContraseña = new javax.swing.JTextField();
        lblTextoVerificacion = new javax.swing.JLabel();
        lblTiempoRegresivo = new javax.swing.JLabel();
        btnDesbloquear1 = new javax.swing.JButton();
        btnDesbloquear2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 245, 248));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(242, 245, 248));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        bginiciosesion.setLayout(new java.awt.GridBagLayout());

        lblequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblequipo.setForeground(new java.awt.Color(0, 86, 150));
        lblequipo.setText("Equipo #");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 95, 0, 0);
        bginiciosesion.add(lblequipo, gridBagConstraints);

        lbl_numerodequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_numerodequipo.setForeground(new java.awt.Color(0, 86, 150));
        lbl_numerodequipo.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 2, 0, 0);
        bginiciosesion.add(lbl_numerodequipo, gridBagConstraints);

        lblubicacion_centro_computo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblubicacion_centro_computo.setForeground(new java.awt.Color(102, 102, 102));
        lblubicacion_centro_computo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblubicacion_centro_computo.setText("Centro de Cómputo: Laboratorio Biblioteca");
        lblubicacion_centro_computo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 35, 0, 0);
        bginiciosesion.add(lblubicacion_centro_computo, gridBagConstraints);

        lblip.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblip.setForeground(new java.awt.Color(102, 102, 102));
        lblip.setText("IP: 192.168.1.115");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        bginiciosesion.add(lblip, gridBagConstraints);

        panelContendedorestadoyalumno.setBackground(new java.awt.Color(210, 228, 255));
        panelContendedorestadoyalumno.setForeground(new java.awt.Color(0, 86, 150));
        panelContendedorestadoyalumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltextoalumno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltextoalumno.setForeground(new java.awt.Color(0, 86, 150));
        lbltextoalumno.setText("Alumno");
        panelContendedorestadoyalumno.add(lbltextoalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        lblTextoestadoactual.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblTextoestadoactual.setForeground(new java.awt.Color(0, 86, 150));
        lblTextoestadoactual.setText("Estado Actual");
        panelContendedorestadoyalumno.add(lblTextoestadoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblEstadoActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstadoActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstadoActual.setText("Dsponible");
        panelContendedorestadoyalumno.add(lblEstadoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        lblNombredelAlumno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombredelAlumno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredelAlumno.setText("Edgar Hiipolito");
        panelContendedorestadoyalumno.add(lblNombredelAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 30, 130, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 25, 0, 10);
        bginiciosesion.add(panelContendedorestadoyalumno, gridBagConstraints);

        lbltextocontraseña.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbltextocontraseña.setForeground(new java.awt.Color(102, 102, 102));
        lbltextocontraseña.setText("Contraseña del Alumno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        bginiciosesion.add(lbltextocontraseña, gridBagConstraints);

        txtinnsertarContraseña.setBackground(new java.awt.Color(240, 241, 241));
        txtinnsertarContraseña.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtinnsertarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinnsertarContraseñaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 25, 0, 10);
        bginiciosesion.add(txtinnsertarContraseña, gridBagConstraints);

        lblTextoVerificacion.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblTextoVerificacion.setForeground(new java.awt.Color(102, 102, 102));
        lblTextoVerificacion.setText("Verificando estado en:");
        lblTextoVerificacion.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        bginiciosesion.add(lblTextoVerificacion, gridBagConstraints);

        lblTiempoRegresivo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblTiempoRegresivo.setForeground(new java.awt.Color(102, 102, 102));
        lblTiempoRegresivo.setText("30");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        bginiciosesion.add(lblTiempoRegresivo, gridBagConstraints);

        btnDesbloquear1.setBackground(new java.awt.Color(242, 242, 242));
        btnDesbloquear1.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        btnDesbloquear1.setText("Liberar Equipo");
        btnDesbloquear1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesbloquear1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 20, 10);
        bginiciosesion.add(btnDesbloquear1, gridBagConstraints);

        btnDesbloquear2.setBackground(new java.awt.Color(0, 72, 128));
        btnDesbloquear2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDesbloquear2.setForeground(new java.awt.Color(255, 255, 255));
        btnDesbloquear2.setText("Desbloquear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 25, 0, 10);
        bginiciosesion.add(btnDesbloquear2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bginiciosesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtinnsertarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusGained
        // TODO add your handling code here:
        if (txtinnsertarContraseña.getText().equals("Ingrese su Contraseña")) {
            txtinnsertarContraseña.setText("");
            txtinnsertarContraseña.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtinnsertarContraseñaFocusGained

    private void txtinnsertarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinnsertarContraseñaFocusLost
        // TODO add your handling code here:
        if (txtinnsertarContraseña.getText().isEmpty()) {
            txtinnsertarContraseña.setText("Ingrese su Contraseña");
            txtinnsertarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtinnsertarContraseñaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bginiciosesion;
    private javax.swing.JButton btnDesbloquear1;
    private javax.swing.JButton btnDesbloquear2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstadoActual;
    private javax.swing.JLabel lblNombredelAlumno;
    private javax.swing.JLabel lblTextoVerificacion;
    private javax.swing.JLabel lblTextoestadoactual;
    private javax.swing.JLabel lblTiempoRegresivo;
    private javax.swing.JLabel lbl_numerodequipo;
    private javax.swing.JLabel lblequipo;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbltextoalumno;
    private javax.swing.JLabel lbltextocontraseña;
    private javax.swing.JLabel lblubicacion_centro_computo;
    private javax.swing.JPanel panelContendedorestadoyalumno;
    private javax.swing.JTextField txtinnsertarContraseña;
    // End of variables declaration//GEN-END:variables
}
