/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author golea
 */
public class Pantalla_desbloqueo_alumno extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla_desbloqueo_alumno
     */
    public Pantalla_desbloqueo_alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        bginiciosesion = new javax.swing.JPanel();
        lblequipo = new javax.swing.JLabel();
        lbl_numerodequipo = new javax.swing.JLabel();
        lblubicacion_centro_computo = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        panelContendedorestadoyalumno = new javax.swing.JPanel();
        lbltextoalumno = new javax.swing.JLabel();
        lblejecutando = new javax.swing.JLabel();
        lblEstadoActual = new javax.swing.JLabel();
        lblNombredelAlumno = new javax.swing.JLabel();
        btnDesbloquear1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(242, 245, 248));

        bginiciosesion.setLayout(new java.awt.GridBagLayout());

        lblequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblequipo.setForeground(new java.awt.Color(0, 86, 150));
        lblequipo.setText("Equipo #");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 90, 0, 0);
        bginiciosesion.add(lblequipo, gridBagConstraints);

        lbl_numerodequipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_numerodequipo.setForeground(new java.awt.Color(0, 86, 150));
        lbl_numerodequipo.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 0, 0);
        bginiciosesion.add(lbl_numerodequipo, gridBagConstraints);

        lblubicacion_centro_computo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblubicacion_centro_computo.setForeground(new java.awt.Color(102, 102, 102));
        lblubicacion_centro_computo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblubicacion_centro_computo.setText("Centro de Cómputo: Laboratorio Biblioteca");
        lblubicacion_centro_computo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 0, 0);
        bginiciosesion.add(lblubicacion_centro_computo, gridBagConstraints);

        lblip.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblip.setForeground(new java.awt.Color(102, 102, 102));
        lblip.setText("IP: 192.168.1.115");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 110, 0, 0);
        bginiciosesion.add(lblip, gridBagConstraints);

        panelContendedorestadoyalumno.setBackground(new java.awt.Color(210, 228, 255));
        panelContendedorestadoyalumno.setForeground(new java.awt.Color(0, 86, 150));
        panelContendedorestadoyalumno.setLayout(new java.awt.GridBagLayout());

        lbltextoalumno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbltextoalumno.setForeground(new java.awt.Color(0, 86, 150));
        lbltextoalumno.setText("Alumno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 110, 0, 0);
        panelContendedorestadoyalumno.add(lbltextoalumno, gridBagConstraints);

        lblejecutando.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblejecutando.setForeground(new java.awt.Color(0, 86, 150));
        lblejecutando.setText("Ejecutando");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelContendedorestadoyalumno.add(lblejecutando, gridBagConstraints);

        lblEstadoActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstadoActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstadoActual.setText("Dsponible");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 6, 0);
        panelContendedorestadoyalumno.add(lblEstadoActual, gridBagConstraints);

        lblNombredelAlumno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombredelAlumno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredelAlumno.setText("Edgar Hiipolito");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 21, 6, 9);
        panelContendedorestadoyalumno.add(lblNombredelAlumno, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 20, 0, 10);
        bginiciosesion.add(panelContendedorestadoyalumno, gridBagConstraints);

        btnDesbloquear1.setBackground(new java.awt.Color(242, 242, 242));
        btnDesbloquear1.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        btnDesbloquear1.setText("Liberar Equipo");
        btnDesbloquear1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesbloquear1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 10);
        bginiciosesion.add(btnDesbloquear1, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bginiciosesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bginiciosesion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bginiciosesion;
    private javax.swing.JButton btnDesbloquear1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoActual;
    private javax.swing.JLabel lblNombredelAlumno;
    private javax.swing.JLabel lbl_numerodequipo;
    private javax.swing.JLabel lblejecutando;
    private javax.swing.JLabel lblequipo;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbltextoalumno;
    private javax.swing.JLabel lblubicacion_centro_computo;
    private javax.swing.JPanel panelContendedorestadoyalumno;
    // End of variables declaration//GEN-END:variables
}
